; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; Test FP64-widened FP32 transcendental operations on full-rate FP64 architectures.
; This tests the -amdgpu-use-fp64-for-fp32-trans option.

; RUN: llc -global-isel -mtriple=amdgcn -mcpu=gfx90a %s -o - | FileCheck -check-prefix=GFX90A %s
; RUN: llc -global-isel -mtriple=amdgcn -mcpu=gfx900 %s -o - | FileCheck -check-prefix=GFX900 %s
; RUN: llc -global-isel -mtriple=amdgcn -mcpu=gfx90a -amdgpu-use-fp64-for-fp32-trans=0 %s -o - | FileCheck -check-prefix=GFX90A-DISABLED %s
; RUN: llc -global-isel -mtriple=amdgcn -mcpu=gfx900 -amdgpu-use-fp64-for-fp32-trans=1 %s -o - | FileCheck -check-prefix=GFX900-ENABLED %s

; Test sqrt(f32) - should use FP64 widening on gfx90a (full-rate FP64)
define amdgpu_kernel void @test_sqrt_f32(ptr addrspace(1) %out, float %x) {
; GFX90A-LABEL: test_sqrt_f32:
; GFX90A:       ; %bb.0:
; GFX90A:         v_cvt_f64_f32
; GFX90A:         v_rsq_f64
; GFX90A:         v_fma_f64
; GFX90A:         v_cvt_f32_f64
;
; GFX900-LABEL: test_sqrt_f32:
; GFX900-NOT:     v_cvt_f64_f32
; GFX900-NOT:     v_rsq_f64
;
; GFX90A-DISABLED-LABEL: test_sqrt_f32:
; GFX90A-DISABLED-NOT:   v_cvt_f64_f32
; GFX90A-DISABLED-NOT:   v_rsq_f64
;
; GFX900-ENABLED-LABEL: test_sqrt_f32:
; GFX900-ENABLED:        v_cvt_f64_f32
; GFX900-ENABLED:        v_rsq_f64
; GFX900-ENABLED:        v_fma_f64
; GFX900-ENABLED:        v_cvt_f32_f64
  %sqrt = call float @llvm.sqrt.f32(float %x)
  store float %sqrt, ptr addrspace(1) %out
  ret void
}

; Test 1.0/x (rcp) - should use FP64 widening on gfx90a
define amdgpu_kernel void @test_rcp_f32(ptr addrspace(1) %out, float %x) {
; GFX90A-LABEL: test_rcp_f32:
; GFX90A:       ; %bb.0:
; GFX90A:         v_cvt_f64_f32
; GFX90A:         v_rcp_f64
; GFX90A:         v_fma_f64
; GFX90A:         v_cvt_f32_f64
;
; GFX900-LABEL: test_rcp_f32:
; GFX900-NOT:     v_cvt_f64_f32
; GFX900-NOT:     v_rcp_f64
;
; GFX90A-DISABLED-LABEL: test_rcp_f32:
; GFX90A-DISABLED-NOT:   v_cvt_f64_f32
; GFX90A-DISABLED-NOT:   v_rcp_f64
;
; GFX900-ENABLED-LABEL: test_rcp_f32:
; GFX900-ENABLED:        v_cvt_f64_f32
; GFX900-ENABLED:        v_rcp_f64
; GFX900-ENABLED:        v_fma_f64
; GFX900-ENABLED:        v_cvt_f32_f64
  %rcp = fdiv float 1.0, %x
  store float %rcp, ptr addrspace(1) %out
  ret void
}

; Test rsq via rcp intrinsic - should use FP64 widening on gfx90a
define amdgpu_kernel void @test_rsq_intrinsic_f32(ptr addrspace(1) %out, float %x) {
; GFX90A-LABEL: test_rsq_intrinsic_f32:
; GFX90A:       ; %bb.0:
; GFX90A:         v_cvt_f64_f32
; GFX90A:         v_rsq_f64
; GFX90A:         v_fma_f64
; GFX90A:         v_cvt_f32_f64
;
; GFX900-LABEL: test_rsq_intrinsic_f32:
; GFX900-NOT:     v_cvt_f64_f32
; GFX900-NOT:     v_rsq_f64
;
; GFX90A-DISABLED-LABEL: test_rsq_intrinsic_f32:
; GFX90A-DISABLED-NOT:   v_cvt_f64_f32
; GFX90A-DISABLED-NOT:   v_rsq_f64
;
; GFX900-ENABLED-LABEL: test_rsq_intrinsic_f32:
; GFX900-ENABLED:        v_cvt_f64_f32
; GFX900-ENABLED:        v_rsq_f64
; GFX900-ENABLED:        v_fma_f64
; GFX900-ENABLED:        v_cvt_f32_f64
  %rsq = call float @llvm.amdgcn.rsq.f32(float %x)
  store float %rsq, ptr addrspace(1) %out
  ret void
}

; Test rcp intrinsic - should use FP64 widening on gfx90a
define amdgpu_kernel void @test_rcp_intrinsic_f32(ptr addrspace(1) %out, float %x) {
; GFX90A-LABEL: test_rcp_intrinsic_f32:
; GFX90A:       ; %bb.0:
; GFX90A:         v_cvt_f64_f32
; GFX90A:         v_rcp_f64
; GFX90A:         v_fma_f64
; GFX90A:         v_cvt_f32_f64
;
; GFX900-LABEL: test_rcp_intrinsic_f32:
; GFX900-NOT:     v_cvt_f64_f32
; GFX900-NOT:     v_rcp_f64
;
; GFX90A-DISABLED-LABEL: test_rcp_intrinsic_f32:
; GFX90A-DISABLED-NOT:   v_cvt_f64_f32
; GFX90A-DISABLED-NOT:   v_rcp_f64
;
; GFX900-ENABLED-LABEL: test_rcp_intrinsic_f32:
; GFX900-ENABLED:        v_cvt_f64_f32
; GFX900-ENABLED:        v_rcp_f64
; GFX900-ENABLED:        v_fma_f64
; GFX900-ENABLED:        v_cvt_f32_f64
  %rcp = call float @llvm.amdgcn.rcp.f32(float %x)
  store float %rcp, ptr addrspace(1) %out
  ret void
}

; Test that afn flag bypasses FP64 widening (uses fast approximation)
define amdgpu_kernel void @test_sqrt_f32_afn(ptr addrspace(1) %out, float %x) {
; GFX90A-LABEL: test_sqrt_f32_afn:
; GFX90A:       ; %bb.0:
; GFX90A:         v_sqrt_f32
; GFX90A-NOT:     v_cvt_f64_f32
; GFX90A-NOT:     v_rsq_f64
;
; GFX900-LABEL: test_sqrt_f32_afn:
; GFX900:         v_sqrt_f32
; GFX900-NOT:     v_cvt_f64_f32
; GFX900-NOT:     v_rsq_f64
  %sqrt = call afn float @llvm.sqrt.f32(float %x)
  store float %sqrt, ptr addrspace(1) %out
  ret void
}

; Test fdiv x/y should benefit from improved rcp
define amdgpu_kernel void @test_fdiv_f32(ptr addrspace(1) %out, float %x, float %y) {
; GFX90A-LABEL: test_fdiv_f32:
; GFX90A:       ; %bb.0:
; Division sequence - check it uses the divisionintermediate steps
;
; GFX900-LABEL: test_fdiv_f32:
; GFX900:       ; %bb.0:
  %div = fdiv float %x, %y
  store float %div, ptr addrspace(1) %out
  ret void
}

declare float @llvm.sqrt.f32(float)
declare float @llvm.amdgcn.rcp.f32(float)
declare float @llvm.amdgcn.rsq.f32(float)
