; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV32I

define i32 @aligner(i16 zeroext %a) nounwind {
; RV32I-LABEL: aligner:
; RV32I:       # %bb.0:
; RV32I-NEXT:    lui a1, 32
; RV32I-NEXT:    addi a1, a1, -16
; RV32I-NEXT:    addi a0, a0, 15
; RV32I-NEXT:    and a0, a0, a1
; RV32I-NEXT:    ret
	%1 = zext i16 %a to i32
	%2 = add i32 %1, 15
	%3 = and i32 %2, -16
	ret i32 %3
}
