; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV32I

define i32 @shiftedmask_20() nounwind {
; RV32I-LABEL: shiftedmask_20:
; RV32I:       # %bb.0:
; RV32I-NEXT:    addi a0, zero, -1
; RV32I-NEXT:    srli a0, a0, 20
; RV32I-NEXT:    ret
  ret i32 4095
}

define i32 @shiftedmask_17() nounwind {
; RV32I-LABEL: shiftedmask_17:
; RV32I:       # %bb.0:
; RV32I-NEXT:    addi a0, zero, -1
; RV32I-NEXT:    srli a0, a0, 17
; RV32I-NEXT:    ret
  ret i32 32767
}

define i32 @shiftedmask_16() nounwind {
; RV32I-LABEL: shiftedmask_16:
; RV32I:       # %bb.0:
; RV32I-NEXT:    addi a0, zero, -1
; RV32I-NEXT:    srli a0, a0, 16
; RV32I-NEXT:    ret
  ret i32 65535
}

define i32 @shiftedmask_15() nounwind {
; RV32I-LABEL: shiftedmask_15:
; RV32I:       # %bb.0:
; RV32I-NEXT:    addi a0, zero, -1
; RV32I-NEXT:    srli a0, a0, 15
; RV32I-NEXT:    ret
  ret i32 131071
}

define i32 @shiftedmask_8() nounwind {
; RV32I-LABEL: shiftedmask_8:
; RV32I:       # %bb.0:
; RV32I-NEXT:    addi a0, zero, -1
; RV32I-NEXT:    srli a0, a0, 8
; RV32I-NEXT:    ret
  ret i32 16777215
}

define i32 @shiftedmask_4() nounwind {
; RV32I-LABEL: shiftedmask_4:
; RV32I:       # %bb.0:
; RV32I-NEXT:    addi a0, zero, -1
; RV32I-NEXT:    srli a0, a0, 4
; RV32I-NEXT:    ret
  ret i32 268435455
}

define i32 @shiftedmask_31() nounwind {
; RV32I-LABEL: shiftedmask_31:
; RV32I:       # %bb.0:
; RV32I-NEXT:    addi a0, zero, 1
; RV32I-NEXT:    ret
  ret i32 1
}

define i32 @shiftedmask_21() nounwind {
; RV32I-LABEL: shiftedmask_21:
; RV32I:       # %bb.0:
; RV32I-NEXT:    addi a0, zero, 2047
; RV32I-NEXT:    ret
  ret i32 2047
}
